### ISSUE TITLE
Fahrenheit <-> Celcius conversion

### ISSUE THREAD

**Issue by martintrojer** [martintrojer/frinj#3]
Implemented as a (Frink) function in units.txt, ignored by the frinj parser.

**Comment by WhittlesJr** [comment]
I spent a bunch of time trying to figure out how to do this conversion with this library until I found this issue. Any chance this could be resolved at this point?

**Comment by WhittlesJr** [comment]
It seems silly that I have to have this type of basic function in my own util namespace:

```
(defn fahrenheit-to-celsius [value]
  (* (- (double value) 32) 5/9))
```

Yet for as much time as I've spent trying to find an existing implementation somewhere, I've had no luck.
